# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DungeonEngineer.ui'
#
# Created: Fri May  8 15:39:46 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 577)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Documents/Engineer Cog.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(640, 0, 161, 461))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.btn_Random_Loot = QtGui.QPushButton(self.tab)
        self.btn_Random_Loot.setGeometry(QtCore.QRect(10, 10, 121, 23))
        self.btn_Random_Loot.setObjectName(_fromUtf8("btn_Random_Loot"))
        self.btn_Potion = QtGui.QPushButton(self.tab)
        self.btn_Potion.setGeometry(QtCore.QRect(10, 40, 121, 23))
        self.btn_Potion.setObjectName(_fromUtf8("btn_Potion"))
        self.btn_Weapon = QtGui.QPushButton(self.tab)
        self.btn_Weapon.setGeometry(QtCore.QRect(10, 70, 121, 23))
        self.btn_Weapon.setObjectName(_fromUtf8("btn_Weapon"))
        self.btn_Armor = QtGui.QPushButton(self.tab)
        self.btn_Armor.setGeometry(QtCore.QRect(10, 100, 121, 23))
        self.btn_Armor.setObjectName(_fromUtf8("btn_Armor"))
        self.btn_Common = QtGui.QPushButton(self.tab)
        self.btn_Common.setGeometry(QtCore.QRect(10, 130, 121, 23))
        self.btn_Common.setObjectName(_fromUtf8("btn_Common"))
        self.btn_Uncommon = QtGui.QPushButton(self.tab)
        self.btn_Uncommon.setGeometry(QtCore.QRect(10, 160, 121, 23))
        self.btn_Uncommon.setObjectName(_fromUtf8("btn_Uncommon"))
        self.btn_Rare = QtGui.QPushButton(self.tab)
        self.btn_Rare.setGeometry(QtCore.QRect(10, 190, 121, 23))
        self.btn_Rare.setObjectName(_fromUtf8("btn_Rare"))
        self.btn_Very_Rare = QtGui.QPushButton(self.tab)
        self.btn_Very_Rare.setGeometry(QtCore.QRect(10, 220, 121, 23))
        self.btn_Very_Rare.setObjectName(_fromUtf8("btn_Very_Rare"))
        self.btn_Legendary = QtGui.QPushButton(self.tab)
        self.btn_Legendary.setGeometry(QtCore.QRect(10, 250, 121, 23))
        self.btn_Legendary.setObjectName(_fromUtf8("btn_Legendary"))
        self.btn_Gold = QtGui.QPushButton(self.tab)
        self.btn_Gold.setGeometry(QtCore.QRect(10, 280, 121, 23))
        self.btn_Gold.setObjectName(_fromUtf8("btn_Gold"))
        self.btn_Treasure = QtGui.QPushButton(self.tab)
        self.btn_Treasure.setGeometry(QtCore.QRect(10, 310, 121, 23))
        self.btn_Treasure.setObjectName(_fromUtf8("btn_Treasure"))
        self.btn_Scroll = QtGui.QPushButton(self.tab)
        self.btn_Scroll.setGeometry(QtCore.QRect(10, 340, 121, 23))
        self.btn_Scroll.setObjectName(_fromUtf8("btn_Scroll"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.btn_Lingering_Injuries = QtGui.QPushButton(self.tab_4)
        self.btn_Lingering_Injuries.setGeometry(QtCore.QRect(10, 10, 121, 23))
        self.btn_Lingering_Injuries.setObjectName(_fromUtf8("btn_Lingering_Injuries"))
        self.btn_Madness = QtGui.QPushButton(self.tab_4)
        self.btn_Madness.setGeometry(QtCore.QRect(10, 420, 121, 23))
        self.btn_Madness.setObjectName(_fromUtf8("btn_Madness"))
        self.btn_Wild_Magic = QtGui.QPushButton(self.tab_4)
        self.btn_Wild_Magic.setGeometry(QtCore.QRect(10, 40, 121, 23))
        self.btn_Wild_Magic.setObjectName(_fromUtf8("btn_Wild_Magic"))
        self.btn_Weather = QtGui.QPushButton(self.tab_4)
        self.btn_Weather.setGeometry(QtCore.QRect(10, 70, 121, 23))
        self.btn_Weather.setObjectName(_fromUtf8("btn_Weather"))
        self.btn_Traps = QtGui.QPushButton(self.tab_4)
        self.btn_Traps.setGeometry(QtCore.QRect(10, 100, 121, 23))
        self.btn_Traps.setObjectName(_fromUtf8("btn_Traps"))
        self.label_Random_Encounter_2 = QtGui.QLabel(self.tab_4)
        self.label_Random_Encounter_2.setGeometry(QtCore.QRect(10, 390, 31, 16))
        self.label_Random_Encounter_2.setObjectName(_fromUtf8("label_Random_Encounter_2"))
        self.comboBox_Madness = QtGui.QComboBox(self.tab_4)
        self.comboBox_Madness.setGeometry(QtCore.QRect(40, 390, 91, 22))
        self.comboBox_Madness.setObjectName(_fromUtf8("comboBox_Madness"))
        self.comboBox_Madness.addItem(_fromUtf8(""))
        self.comboBox_Madness.addItem(_fromUtf8(""))
        self.comboBox_Madness.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.btn_Random_Names = QtGui.QPushButton(self.tab_3)
        self.btn_Random_Names.setGeometry(QtCore.QRect(10, 10, 121, 23))
        self.btn_Random_Names.setObjectName(_fromUtf8("btn_Random_Names"))
        self.btn_Drow_Name = QtGui.QPushButton(self.tab_3)
        self.btn_Drow_Name.setGeometry(QtCore.QRect(10, 40, 121, 23))
        self.btn_Drow_Name.setObjectName(_fromUtf8("btn_Drow_Name"))
        self.btn_Item_Origin = QtGui.QPushButton(self.tab_3)
        self.btn_Item_Origin.setGeometry(QtCore.QRect(10, 130, 121, 23))
        self.btn_Item_Origin.setObjectName(_fromUtf8("btn_Item_Origin"))
        self.btn_Enchantment = QtGui.QPushButton(self.tab_3)
        self.btn_Enchantment.setGeometry(QtCore.QRect(10, 70, 121, 23))
        self.btn_Enchantment.setObjectName(_fromUtf8("btn_Enchantment"))
        self.btn_Plot_Hook = QtGui.QPushButton(self.tab_3)
        self.btn_Plot_Hook.setGeometry(QtCore.QRect(10, 100, 121, 23))
        self.btn_Plot_Hook.setObjectName(_fromUtf8("btn_Plot_Hook"))
        self.btn_Downtime = QtGui.QPushButton(self.tab_3)
        self.btn_Downtime.setGeometry(QtCore.QRect(10, 420, 121, 23))
        self.btn_Downtime.setObjectName(_fromUtf8("btn_Downtime"))
        self.btn_Riddle = QtGui.QPushButton(self.tab_3)
        self.btn_Riddle.setGeometry(QtCore.QRect(10, 160, 121, 23))
        self.btn_Riddle.setObjectName(_fromUtf8("btn_Riddle"))
        self.btn_Puzzle = QtGui.QPushButton(self.tab_3)
        self.btn_Puzzle.setGeometry(QtCore.QRect(10, 190, 121, 23))
        self.btn_Puzzle.setObjectName(_fromUtf8("btn_Puzzle"))
        self.label_Random_Encounter_3 = QtGui.QLabel(self.tab_3)
        self.label_Random_Encounter_3.setGeometry(QtCore.QRect(10, 390, 31, 16))
        self.label_Random_Encounter_3.setObjectName(_fromUtf8("label_Random_Encounter_3"))
        self.comboBox_Downtime = QtGui.QComboBox(self.tab_3)
        self.comboBox_Downtime.setGeometry(QtCore.QRect(40, 390, 91, 22))
        self.comboBox_Downtime.setObjectName(_fromUtf8("comboBox_Downtime"))
        self.comboBox_Downtime.addItem(_fromUtf8(""))
        self.comboBox_Downtime.addItem(_fromUtf8(""))
        self.comboBox_Downtime.addItem(_fromUtf8(""))
        self.label_Spellbook = QtGui.QLabel(self.tab_3)
        self.label_Spellbook.setGeometry(QtCore.QRect(10, 330, 31, 16))
        self.label_Spellbook.setObjectName(_fromUtf8("label_Spellbook"))
        self.comboBox_Spellbook = QtGui.QComboBox(self.tab_3)
        self.comboBox_Spellbook.setGeometry(QtCore.QRect(40, 330, 91, 22))
        self.comboBox_Spellbook.setObjectName(_fromUtf8("comboBox_Spellbook"))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.comboBox_Spellbook.addItem(_fromUtf8(""))
        self.btn_Spellbook = QtGui.QPushButton(self.tab_3)
        self.btn_Spellbook.setGeometry(QtCore.QRect(10, 360, 121, 23))
        self.btn_Spellbook.setObjectName(_fromUtf8("btn_Spellbook"))
        self.btn_QuestGen = QtGui.QPushButton(self.tab_3)
        self.btn_QuestGen.setGeometry(QtCore.QRect(10, 220, 121, 23))
        self.btn_QuestGen.setObjectName(_fromUtf8("btn_QuestGen"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(670, 480, 121, 71))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_Level = QtGui.QLabel(self.groupBox)
        self.label_Level.setGeometry(QtCore.QRect(20, 20, 46, 21))
        self.label_Level.setObjectName(_fromUtf8("label_Level"))
        self.label_Difficulty = QtGui.QLabel(self.groupBox)
        self.label_Difficulty.setGeometry(QtCore.QRect(10, 40, 46, 21))
        self.label_Difficulty.setObjectName(_fromUtf8("label_Difficulty"))
        self.comboBox_Difficulty = QtGui.QComboBox(self.groupBox)
        self.comboBox_Difficulty.setGeometry(QtCore.QRect(60, 40, 61, 22))
        self.comboBox_Difficulty.setObjectName(_fromUtf8("comboBox_Difficulty"))
        self.comboBox_Difficulty.addItem(_fromUtf8(""))
        self.comboBox_Difficulty.addItem(_fromUtf8(""))
        self.comboBox_Difficulty.addItem(_fromUtf8(""))
        self.spinBox_Level = QtGui.QSpinBox(self.groupBox)
        self.spinBox_Level.setGeometry(QtCore.QRect(60, 20, 61, 16))
        self.spinBox_Level.setMinimum(1)
        self.spinBox_Level.setMaximum(20)
        self.spinBox_Level.setObjectName(_fromUtf8("spinBox_Level"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 621, 541))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.btnClear = QtGui.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(640, 520, 21, 23))
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dungeon Engineer Toolkit", None))
        self.btn_Random_Loot.setText(_translate("MainWindow", "Random Loot", None))
        self.btn_Potion.setText(_translate("MainWindow", "Potion", None))
        self.btn_Weapon.setText(_translate("MainWindow", "Weapon", None))
        self.btn_Armor.setText(_translate("MainWindow", "Armor", None))
        self.btn_Common.setText(_translate("MainWindow", "Common", None))
        self.btn_Uncommon.setText(_translate("MainWindow", "Uncommon", None))
        self.btn_Rare.setText(_translate("MainWindow", "Rare", None))
        self.btn_Very_Rare.setText(_translate("MainWindow", "Very Rare", None))
        self.btn_Legendary.setText(_translate("MainWindow", "Legendary", None))
        self.btn_Gold.setText(_translate("MainWindow", "Gold", None))
        self.btn_Treasure.setText(_translate("MainWindow", "Treasure", None))
        self.btn_Scroll.setText(_translate("MainWindow", "Scroll", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Loot", None))
        self.btn_Lingering_Injuries.setText(_translate("MainWindow", "Lingering Injuries", None))
        self.btn_Madness.setText(_translate("MainWindow", "Madness", None))
        self.btn_Wild_Magic.setText(_translate("MainWindow", "Wild Magic", None))
        self.btn_Weather.setText(_translate("MainWindow", "Weather", None))
        self.btn_Traps.setText(_translate("MainWindow", "Traps", None))
        self.label_Random_Encounter_2.setText(_translate("MainWindow", "Type:", None))
        self.comboBox_Madness.setItemText(0, _translate("MainWindow", "Short-term", None))
        self.comboBox_Madness.setItemText(1, _translate("MainWindow", "Long-term", None))
        self.comboBox_Madness.setItemText(2, _translate("MainWindow", "Indefinite", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Encounter", None))
        self.btn_Random_Names.setText(_translate("MainWindow", "Random Names", None))
        self.btn_Drow_Name.setText(_translate("MainWindow", "Drow Name", None))
        self.btn_Item_Origin.setText(_translate("MainWindow", "Item Origin", None))
        self.btn_Enchantment.setText(_translate("MainWindow", "Enchantment", None))
        self.btn_Plot_Hook.setText(_translate("MainWindow", "Plot Hook", None))
        self.btn_Downtime.setText(_translate("MainWindow", "Downtime", None))
        self.btn_Riddle.setText(_translate("MainWindow", "Riddle", None))
        self.btn_Puzzle.setText(_translate("MainWindow", "Puzzle", None))
        self.label_Random_Encounter_3.setText(_translate("MainWindow", "Type:", None))
        self.comboBox_Downtime.setItemText(0, _translate("MainWindow", "Training", None))
        self.comboBox_Downtime.setItemText(1, _translate("MainWindow", "Carousing", None))
        self.comboBox_Downtime.setItemText(2, _translate("MainWindow", "Sell Magic Item", None))
        self.label_Spellbook.setText(_translate("MainWindow", "Class:", None))
        self.comboBox_Spellbook.setItemText(0, _translate("MainWindow", "bard", None))
        self.comboBox_Spellbook.setItemText(1, _translate("MainWindow", "cleric", None))
        self.comboBox_Spellbook.setItemText(2, _translate("MainWindow", "druid", None))
        self.comboBox_Spellbook.setItemText(3, _translate("MainWindow", "paladin", None))
        self.comboBox_Spellbook.setItemText(4, _translate("MainWindow", "ranger", None))
        self.comboBox_Spellbook.setItemText(5, _translate("MainWindow", "sorcerer", None))
        self.comboBox_Spellbook.setItemText(6, _translate("MainWindow", "warlock", None))
        self.comboBox_Spellbook.setItemText(7, _translate("MainWindow", "wizard", None))
        self.btn_Spellbook.setText(_translate("MainWindow", "Spellbook", None))
        self.btn_QuestGen.setText(_translate("MainWindow", "Quest Generator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Utility", None))
        self.groupBox.setTitle(_translate("MainWindow", "Party Info", None))
        self.label_Level.setText(_translate("MainWindow", "Level:", None))
        self.label_Difficulty.setText(_translate("MainWindow", "Difficulty:", None))
        self.comboBox_Difficulty.setItemText(0, _translate("MainWindow", "Easy", None))
        self.comboBox_Difficulty.setItemText(1, _translate("MainWindow", "Average", None))
        self.comboBox_Difficulty.setItemText(2, _translate("MainWindow", "Difficult", None))
        self.btnClear.setText(_translate("MainWindow", "C", None))

